# Generated by Django 5.0.14 on 2025-05-06 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='folder_path',
            field=models.CharField(default='root', max_length=255),
        ),
    ]
