# Generated by Django 5.0.14 on 2025-05-06 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_uploadedfile_folder_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedfile',
            name='folder_path',
        ),
    ]
